### ISSUE TITLE
[Issue] Mod-Pack's Install Had Some Issues With H3VR

### ISSUE THREAD

**Issue by CptAnonymou5** [Kesomannen/gale#164]
Hello,

Thank you for creating such a fantastic tool! However, I’ve encountered an issue while trying to install some mods. I’ve noticed duplicate mods, which may have resulted from installing multiple mod packs or updating several mods at once.

The mod in question is linked below. (USECAI) Unfortunately, I cannot access its directory to delete the folders and attempted a fresh installation with the same results. I see three instances of the same mod listed, one of which is from my manual installation attempt, which was unsuccessful due to my inability to delete it.

Thank you for your assistance!

[Link to the mod & screenshots below]

https://thunderstore.io/c/h3vr/p/JerryAr/USECAI/

https://imgur.com/a/75fhttZ  - Sorry about the color being washed out not sure whats going on with that.

**Comment by Kesomannen** [comment]
Uninstallation of local mods is fixed in 1.1.2, does that resolve your issue?

**Comment by CptAnonymou5** [comment]
I'm still having issues with mod packs that I don't get on Thunderstore. I will wait a few updates and try again. I really enjoy the Mod Installer keep up the great work!

Recently, I’ve noticed that when I install a mod pack, Gale prompts me to update several mods from the list. However, I encounter multiple errors indicating that certain mods couldn’t be found. I assume these may be dependencies or mods that were missed in the pack. As a result, I end up having to install these mods manually to continue updating the mod list.

Thank you for your attention to this matter!

**Comment by Kesomannen** [comment]
Which mods does it not found? What's the modpack you're trying to install?

**Comment by Kesomannen** [comment]
Stale
